import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import anganyAuthSidebar from './docs/api/angany-auth/sidebar';
import anganyConfigurationSidebar from './docs/api/angany-configuration/sidebar';
import anganyAppDataSidebar from './docs/api/angany-app-data/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [
      {
      type: 'category',
      label: 'Welcome',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'welcome'
        },
      ],
    },
    {
      type: 'category',
      label: 'Portal Documentation',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'angany-portal'
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Authentication',
          collapsible: true,
          collapsed: true,
          items: anganyAuthSidebar,
        },
        {
          type: 'category',
          label: 'Configuration',
          collapsible: true,
          collapsed: true,
          items: anganyConfigurationSidebar,
        },
        {
          type: 'category',
          label: 'App Data',
          collapsible: true,
          collapsed: true,
          items: anganyAppDataSidebar,
        }
      ]
    }
  ],
};

export default sidebars;
